/**
 * Legacy schema file for backwards compatibility
 * Now re-exports from types.ts (static data types)
 *
 * Previously auto-generated by Directus, now manually maintained
 */

export * from './types'
